### ISSUE TITLE
contains not working against IIFE objects

### ISSUE THREAD

**Issue by martin-gillen** [testdouble/testdouble.js#192]
If the subject under test and/or the arg passed to the contains() matcher was created using [IIFE](http://benalman.com/news/2010/11/immediately-invoked-function-expression/) then the matcher is not working correctly.

Here is an example:

```js
            it('TD contains with IIFE objects', () => {

                var brew = td.function();

                var Container = (function () {
                    function Container() {
                    }
                    return Container;
                }());

                var Coffee = (function () {
                    function Coffee() {
                        this.container = new Container();
                    }
                    return Coffee;
                }());

                var smallCoffeeContainer = new Coffee();
                smallCoffeeContainer.container.size = 'S';

                var largeCoffeeContainer = new Coffee();
                largeCoffeeContainer.container.size = 'L';

                var smallCupOfCoffee = new Coffee();
                smallCupOfCoffee.container.size = 'S';
                smallCupOfCoffee.container.type = 'cup';
                smallCupOfCoffee.ingredient = 'beans';

                console.log('smallCupOfCoffee', JSON.stringify(smallCupOfCoffee));
                console.log('smallCoffeeContainer', JSON.stringify(smallCoffeeContainer));
                console.log('largeCoffeeContainer', JSON.stringify(largeCoffeeContainer));

                td.when(brew(td.matchers.anything())).thenReturn('little steam');
                expect(brew(smallCupOfCoffee)).to.equal('little steam');
                td.verify(brew(td.matchers.contains(smallCoffeeContainer)));
        
            });
```
This produces:

```
    Error: Unsatisfied verification on test double.
  Wanted:
    - called with `(contains("[object Object]"))`.
  But was actually called:
    - called with `("[object Object]")`.
      at Object.fail (node_modules\testdouble\lib\log.js:21:13)
      at Object.module.exports [as verify] (node_modules\testdouble\lib\verify.js:28:20)
      at Context.<anonymous> (build\test\controllers\services-controller.tests.js:182:20)
```

The three console.log lines produced:

```
smallCupOfCoffee {"container":{"size":"S","type":"cup"},"ingredient":"beans"}
smallCoffeeContainer {"container":{"size":"S"}}
largeCoffeeContainer {"container":{"size":"L"}}
```

If I refactor the test to use objects which have been created declaratively:

```js
            it('TD contains with simple objects', () => {

                var brew = td.function()

                let smallCoffeeContainer = {
                    container:  {
                        size: 'S'
                    }
                };

                let largeCoffeeContainer = {
                    container:  {
                        size: 'L'
                    }
                };

                let smallCupOfCoffee = {
                    container:  {
                        size: 'S',
                        type: 'cup'
                    },
                    ingredient: 'beans'
                };

                console.log('smallCupOfCoffee', JSON.stringify(smallCupOfCoffee));
                console.log('smallCoffeeContainer', JSON.stringify(smallCoffeeContainer));
                console.log('largeCoffeeContainer', JSON.stringify(largeCoffeeContainer));

                td.when(brew(td.matchers.anything())).thenReturn('little steam');
                expect(brew(smallCupOfCoffee)).to.equal('little steam'); 
                td.verify(brew(td.matchers.contains(smallCoffeeContainer)));
            });
```

In this case it just works.   The console logs print the same.

I can make the IIFE case work by stripping the functions out of the objects before invoking the tests:

```js
            it('TD contains with IIFE objects', () => {

                var brew = td.function();

                var Container = (function () {
                    function Container() {
                    }
                    return Container;
                }());

                var Coffee = (function () {
                    function Coffee() {
                        this.container = new Container();
                    }
                    return Coffee;
                }());

                var smallCoffeeContainer = new Coffee();
                smallCoffeeContainer.container.size = 'S';

                var largeCoffeeContainer = new Coffee();
                largeCoffeeContainer.container.size = 'L';

                var smallCupOfCoffee = new Coffee();
                smallCupOfCoffee.container.size = 'S';
                smallCupOfCoffee.container.type = 'cup';
                smallCupOfCoffee.ingredient = 'beans';

                console.log('smallCupOfCoffee', JSON.stringify(smallCupOfCoffee));
                console.log('smallCoffeeContainer', JSON.stringify(smallCoffeeContainer));
                console.log('largeCoffeeContainer', JSON.stringify(largeCoffeeContainer));

                smallCupOfCoffee = JSON.parse(JSON.stringify(smallCupOfCoffee));
                smallCoffeeContainer = JSON.parse(JSON.stringify(smallCoffeeContainer));

                td.when(brew(td.matchers.anything())).thenReturn('little steam');
                expect(brew(smallCupOfCoffee)).to.equal('little steam');
                td.verify(brew(td.matchers.contains(smallCoffeeContainer)));
        
            });
```

... but that doesn't help me when the subject under test is creating the IIFE.

**Comment by searls** [comment]
This is a fairly long example and what was going on didn't immediately jump out to me. (Given what I remember of using IIFEs, the issue is probably the result of somebody comparing something by reference, but that reference changing if the IIFE is re-invoked)

I threw triage of this issue on the backlog, but would encourage you to attempt to debug the root problem on your own if you need a quick resolution
