### ISSUE TITLE
td.constructor() ReferenceError: td is not defined

### ISSUE THREAD

**Issue by ruhkopf** [testdouble/testdouble.js#279]
After upgrading from Testdouble 3.2.2 to 3.2.3 we're seeing the following error:
```
var td = require('testdouble');
var x = td.constructor();

ReferenceError: td is not defined
      at fakeConstructorFromNames (src/node_modules/testdouble/lib/constructor.js:26:35)
      at new exports.default (src/node_modules/testdouble/lib/constructor.js:22:95)
```

**Comment by searls** [comment]
Thanks. Landed in 3.2.4
