### ISSUE TITLE
MockService Not Working in Angular 8

### ISSUE THREAD

**Issue by DineshKumarGovindarajan87** [testdouble/testdouble.js#420]
### Description
MockService test case failed.

### Environment

- [ ] `node -v` output: 10.16.0
- [ ] `npm -v` (or `yarn --version`) output: 6+
- [ ] `npm ls testdouble` (or `yarn list testdouble`) version: 3.3.0

### Failing Test

  TypeError: this.appTitle.setTitle is not a function
            at new AppComponent (http://localhost:9876/_karma_webpack_/webpack:/src/app/app.component.ts:14:19)
            at createClass (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:24580:1)
            at createDirectiveInstance (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:24400:1)
            at createViewNodes (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:35006:1)
            at createRootView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:34878:1)
            at callWithDebugContext (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:36407:1)
            at Object.debugCreateRootView [as createRootView] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:35644:1)
            at ComponentFactory_.create (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:23542:1)
            at initComponent (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/testing.js:3409:1)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:359:1)

### Example Repo
```js
var td = require('testdouble')

// Your steps here.
``` 1. beforeEach(async(() => {
   mockAppTitle = td.object(Title.prototype);

    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      declarations: [
        AppComponent
      ],
      providers: [
       { provide: Title , useValue: mockAppTitle}
      ]
    }).compileComponents();
  }));
  beforeEach(() => {
    fixture = TestBed.createComponent(AppComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
    compiled = fixture.debugElement.nativeElement;
  });
  it('should set tilte in header', () => {
    expect(mockAppTitle.setTitle('Demo'));
  });
});

2. In Constructor I assigned the titleService  and used setTitle('Demo') method. 

How to use mockservice in angular 8. any new syntax updated in testdouble 
![Capture](https://user-images.githubusercontent.com/46916258/60346741-6d2b0680-99d9-11e9-9c17-9e11dffbaa0c.PNG)
![Screen1](https://user-images.githubusercontent.com/46916258/60346743-6d2b0680-99d9-11e9-90af-26c57ce4e903.PNG)
![Screen2](https://user-images.githubusercontent.com/46916258/60346744-6dc39d00-99d9-11e9-993a-afe993283419.PNG)


?
Please revert me any suggestion.

**Comment by DineshKumarGovindarajan87** [comment]
![Screen1](https://user-images.githubusercontent.com/46916258/60346909-ce52da00-99d9-11e9-8e13-adb8a9fce168.PNG)
![Screen2](https://user-images.githubusercontent.com/46916258/60346914-d3178e00-99d9-11e9-99d7-29a85a0c2672.PNG)
![Capture](https://user-images.githubusercontent.com/46916258/60346916-d4e15180-99d9-11e9-8d6a-1b649e5a6bdd.PNG)

**Comment by tgroshon** [comment]
Thanks for taking the time to create an issue and including sample code. We have not had a chance to look into the details of your particular case but should by early next week (perhaps later with the upcoming US Holiday).

Standby! 
:)

**Comment by rosston** [comment]
@DineshKumarGovindarajan87 From the information you have provided, it sounds like you are running into an issue with using Angular's dependency injection system. You might want to investigate more on the Angular side of things to determine how to provide a mocked `Title`.

Additionally, you might want to look at [the documentation for `td.verify`](https://github.com/testdouble/testdouble.js#tdverify-for-verifying-interactions) once you've figured out how to provide the mocked value.

I think we should close this issue for now since I think it is outside of the scope of the testdouble.js project.
