### ISSUE TITLE
Destructuring support fail.

### ISSUE THREAD

**Issue by iamjinme** [testdouble/testdouble.js#424]
### Description
Destructuring modules to use with method **replace**

### Issue

When I try this:
```const { one, two } = td.replace('../any/jsfile');```

Where `jsfile` has:
```module.exports = {
  one,
  two,
};
```

Thrown an error like this:
```
⠧   TypeError: Cannot read property 'length' of undefined
      at Object.length (/home/mirabalj/www/rappi-pay-kyc/node_modules/delegates/index.js:72:24)
      at isArrayLike (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/isArrayLike.js:30:42)
      at keys (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/keys.js:34:10)
      at baseGetAllKeys (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_baseGetAllKeys.js:16:16)
      at getAllKeys (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_getAllKeys.js:13:10)
      at baseClone (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_baseClone.js:153:35)
      at /home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_baseClone.js:160:30
      at arrayEach (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_arrayEach.js:15:9)
      at baseClone (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_baseClone.js:154:3)
      at /home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_baseClone.js:160:30
      at arrayEach (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_arrayEach.js:15:9)
      at baseClone (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_baseClone.js:154:3)
      at /home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_baseClone.js:160:30
      at arrayEach (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_arrayEach.js:15:9)
      at baseClone (/home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_baseClone.js:154:3)
      at /home/mirabalj/www/rappi-pay-kyc/node_modules/testdouble/node_modules/lodash/_baseClone.js:160:30
```

### Environment

- [ ] `node -v` output: v10.16.0
- [ ] `npm -v` (or `yarn --version`) output: 6.10.1
- [ ] `npm ls testdouble` (or `yarn list testdouble`) version: testdouble@3.12.2

**Comment by searls** [comment]
Seems to work for me on latest.

File: `foo.js`:

```js
module.exports = {
  one: function () { return 1 },
  two: function () { return 2 }
}
```

File: `bar.js`
```js
const td = require('testdouble')

const { one, two } = td.replace('./foo')

console.log('one', one)
console.log('two', two)
```

Running `node bar.js` yields output:

```
one [test double for "./foo: .one"]
two [test double for "./foo: .two"]
```

Closing without a reproduction
